INFO - 2024-07-02 06:00:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-02 06:00:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-02 06:00:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-02 06:01:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-02 06:01:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-02 06:01:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-02 06:01:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-02 06:01:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-02 06:15:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-02 06:15:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-07-02 08:47:35 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 185, Array)
#1 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#9 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#5 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-07-02 08:47:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Lokasi->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-02 08:47:42 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 185, Array)
#1 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#9 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#5 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-07-02 08:47:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Lokasi->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-02 08:47:54 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 185, Array)
#1 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#9 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#5 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-07-02 08:47:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Lokasi->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-02 08:48:05 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 185, Array)
#1 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#9 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#5 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-07-02 08:48:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Lokasi->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-02 08:49:15 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 185, Array)
#1 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#9 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#5 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-07-02 08:49:15 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Lokasi->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-02 08:53:29 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 185, Array)
#1 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#9 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#5 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-07-02 08:53:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Lokasi->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-02 08:53:33 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 185, Array)
#1 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#9 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#5 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-07-02 08:53:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Lokasi->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-02 08:57:44 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 185, Array)
#1 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#9 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#5 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-07-02 08:57:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Lokasi->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-02 08:58:16 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 185, Array)
#1 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#9 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#5 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-07-02 08:58:16 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Lokasi->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-02 08:58:28 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 185, Array)
#1 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#9 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#5 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-07-02 08:58:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Lokasi->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-02 08:59:02 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 185, Array)
#1 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#9 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#5 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-07-02 08:59:02 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Lokasi->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-02 08:59:08 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 185, Array)
#1 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#9 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#5 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-07-02 08:59:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Lokasi->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-02 09:02:09 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 185, Array)
#1 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#9 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('http://10.1.46....', 'root', '', 'db-webgis-dasar...', 3306, '', 0)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#8 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\xampp\htdocs\gis-ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\gis-ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\gis-ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\gis-ci4\app\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\gis-ci4\app\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
#5 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(943): App\Controllers\Lokasi->index()
#6 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
#7 C:\xampp\htdocs\gis-ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\gis-ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-07-02 09:02:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: No such host is known. 
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Models\ModelLokasi.php(19): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Lokasi.php(235): App\Models\ModelLokasi->getAllData()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Lokasi->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Lokasi))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
